//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LED_Hive {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Color : global::System.Configuration.ApplicationSettingsBase {
        
        private static Color defaultInstance = ((Color)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Color())));
        
        public static Color Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int MousePrimaryRed {
            get {
                return ((int)(this["MousePrimaryRed"]));
            }
            set {
                this["MousePrimaryRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int MousePrimaryGreen {
            get {
                return ((int)(this["MousePrimaryGreen"]));
            }
            set {
                this["MousePrimaryGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MousePrimaryBlue {
            get {
                return ((int)(this["MousePrimaryBlue"]));
            }
            set {
                this["MousePrimaryBlue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MouseSecondaryRed {
            get {
                return ((int)(this["MouseSecondaryRed"]));
            }
            set {
                this["MouseSecondaryRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int MouseSecondaryGreen {
            get {
                return ((int)(this["MouseSecondaryGreen"]));
            }
            set {
                this["MouseSecondaryGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int MouseSecondaryBlue {
            get {
                return ((int)(this["MouseSecondaryBlue"]));
            }
            set {
                this["MouseSecondaryBlue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192")]
        public int MouseTertiaryRed {
            get {
                return ((int)(this["MouseTertiaryRed"]));
            }
            set {
                this["MouseTertiaryRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MouseTertiaryGreen {
            get {
                return ((int)(this["MouseTertiaryGreen"]));
            }
            set {
                this["MouseTertiaryGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192")]
        public int MouseTertiaryBlue {
            get {
                return ((int)(this["MouseTertiaryBlue"]));
            }
            set {
                this["MouseTertiaryBlue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int KeyboardPrimaryRed {
            get {
                return ((int)(this["KeyboardPrimaryRed"]));
            }
            set {
                this["KeyboardPrimaryRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int KeyboardPrimaryGreen {
            get {
                return ((int)(this["KeyboardPrimaryGreen"]));
            }
            set {
                this["KeyboardPrimaryGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KeyboardPrimaryBlue {
            get {
                return ((int)(this["KeyboardPrimaryBlue"]));
            }
            set {
                this["KeyboardPrimaryBlue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KeyboardSecondaryRed {
            get {
                return ((int)(this["KeyboardSecondaryRed"]));
            }
            set {
                this["KeyboardSecondaryRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int KeyboardSecondaryGreen {
            get {
                return ((int)(this["KeyboardSecondaryGreen"]));
            }
            set {
                this["KeyboardSecondaryGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int KeyboardSecondaryBlue {
            get {
                return ((int)(this["KeyboardSecondaryBlue"]));
            }
            set {
                this["KeyboardSecondaryBlue"] = value;
            }
        }
    }
}
